// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/shortid/index.d.ts
declare module 'shortid' {
// Type definitions for shortid
// Project: https://github.com/dylang/shortid
// Definitions by: Sam Saint-Pettersen <https://github.com/stpettersens>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


export function generate(): string;
export function characters(string: string): string;
export function isValid(id: any): boolean;
export function worker(integer: number): void;
export function seed(float: number): void;
}
